import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css"; // adjust path as needed
import LeftSidebar from "@/components/sidebars/LeftSidebar";
import { RightSidebar } from "@/components/sidebars/RightSidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Sound Wave App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main
      className={`${geistSans.variable} ${geistMono.variable} antialiased flex min-h-screen bg-[#232323]`}
    >
      <div className="w-64">
        <LeftSidebar />
      </div>

      <div className="flex-1 flex justify-center items-center">
        {children}
      </div>

      <div className="w-64">
        <RightSidebar />
      </div>
    </main>
  );
}
